---
- name: Converge
  hosts: all
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Include the role
      ansible.builtin.include_role:
        name: bsmeding.webmin

